name: Label Dependabot security updates

on:
  pull_request_target:
    types: [opened]
    branches:
      - 'dependabot/npm_and_yarn/plugin/javascript-security-*'

permissions:
  pull-requests: write

jobs:
  label-security-updates:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.head_ref, 'javascript-security')
    steps:
      - name: Replace dependencies label with bug
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --remove-label dependencies --add-label bug
